services:
    photosorter:
        image: ghcr.io/salmeister/salmeister/photo-sorter-api/photosorterapi:latest
        container_name: photosorter
        labels:
          - swag=enable
          - swag_address=photosorter
          - swag_url=photosorter.*
          - swag_port=8500
        ports:
          - 8500:8080
        environment:
          - ASPNETCORE_ENVIRONMENT=Production
        volumes:
          - ./logs:/logs
          - /nas/home_content:/mnt/home_content
        restart: unless-stopped
        networks:
          - shared-net
networks:
  shared-net:
    external: true
    name: shared-net
