version: '3.3'
services:
    web:
        image: "dockerhub.salmeister.com/photosorterapi"
        container_name: photosorter
        deploy:
          labels:
            - "com.centurylinklabs.watchtower.enable=false"
        ports:
            - "8500:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        volumes:
            - ./logs:/logs
            - /nas/home_content:/mnt/home_content
        restart: unless-stopped
        network_mode: bridge
