services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    #labels:
    #  - swag=enable #manually set at swag/config/nginx/proxy-conf/bitwarden.subdomain.conf
    networks:
      - shared-net
    restart: unless-stopped
    volumes:
    - /nas/docker/bitwarden/data:/data
    environment:
      - SIGNUPS_ALLOWED=false
      - PUID=1000
      - PGID=1002
      - TZ=America/Chicago
      - WEBSOCKET_ENABLED=true
      - DOMAIN_FILE=/run/secrets/domain
      - ADMIN_TOKEN_FILE=/run/secrets/adminpsswd
    ports:
    - 480:80
    healthcheck:
      disable: true
    secrets:
    - domain
    - adminpsswd
#    labels:
#      - swag=enable
#      - swag_port=480
#      - swag_url=bitwarden.*
secrets:
  domain:
    file: ./domain.txt
  adminpsswd:
    file: ./adminpsswd.txt
networks:
  shared-net:
    external: true
    name: shared-net
