services:
   omada-controller:
     container_name: omada-controller
     image: mbentley/omada-controller:latest
     env_file:
       - ./.env
     network_mode: host
     volumes:
      - ./EAPController/data:/opt/tplink/EAPController/data
      - ./EAPController/work:/opt/tplink/EAPController/work
      - ./EAPController/logs:/opt/tplink/EAPController/logs
     restart: unless-stopped
