services:
   omada-controller:
     container_name: omada-controller
     image: mbentley/omada-controller:latest
     environment:
      - TZ=America/Chicago
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8043
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
     network_mode: host
     volumes:
      - /nas/docker/omada/EAPController/data:/opt/tplink/EAPController/data
      - /nas/docker/omada/EAPController/work:/opt/tplink/EAPController/work
      - /nas/docker/omada/EAPController/logs:/opt/tplink/EAPController/logs
     restart: unless-stopped
