services:
   omada-controller:
     container_name: omada-controller
     image: mbentley/omada-controller:beta-5.14
     env_file:
       - ./.env
     network_mode: host
     ulimits:
      nofile:
        soft: 4096
        hard: 8192
     stop_grace_period: 60s
     volumes:
      - ./EAPController/data:/opt/tplink/EAPController/data
      - ./EAPController/work:/opt/tplink/EAPController/work
      - ./EAPController/logs:/opt/tplink/EAPController/logs
