services:
  mealie:
    image: hkotel/mealie:latest
    container_name: mealie
    labels:
      - swag=enable
      - swag_port=9090
      - swag_url=meals.*
    environment:
      - PUID=1000
      - PGID=1002
      - TZ=America/Chicago
      - ALLOW_SIGNUP=false
      - RECIPE_PUBLIC=false
      - MAX_WORKERS=1
      - DB_ENGINE=sqlite
    ports:
      - "9090:9000"
    volumes:
      - ./data:/app/data
    networks:
      - shared-net
    restart: unless-stopped

networks:
  shared-net:
    external: true
    name: shared-net
