services:
  mosquitto:
    container_name: mosquitto
    image:  eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 9001:9001
    environment:
      - TZ=America/Chicago
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    privileged: true
    ports:
      - 9442:9442
    volumes:
      - ./zigbee/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      # path to zigbee USB device
      - /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0

    environment:
      - TZ=America/Chicago

  zwave:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    devices:
      - "/dev/serial/by-id/usb-0658_0200-if00:/dev/ttyACM0"
    volumes:
      - ./zwavejs/store:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for zwave-js websocket server

  postgresdb:
    image: "postgres:14"
    container_name: "postgres"
    ports:
      - "5432:5432"
    network_mode: bridge
    restart: unless-stopped
    environment:
      - POSTGRES_DB=homeassistant
      - POSTGRES_USER_FILE=/run/secrets/postgres-usr
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-psswd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 5s
      retries: 30
    volumes:
      - /etc/localtime:/etc/localtime
      - ./postgres/hass:/var/lib/postgresql/data
    secrets:
      - postgres-usr
      - postgres-psswd

  influxdb:
    container_name: influxdb
    image: influxdb:1.8.5
    restart: unless-stopped
    network_mode: bridge
    environment:
      - INFLUXDB_REPORTING_DISABLED=false
      - INFLUXDB_ADMIN_USER_FILE=/run/secrets/influx-usr
      - INFLUXDB_ADMIN_PASSWORD_FILE=/run/secrets/influx-psswd
    healthcheck:
      test: "curl -f http://192.168.1.3:8086/ping"
      interval: 30s
      timeout: 5s
      retries: 30
    volumes:
      - ./influxdb/data:/var/lib/influxdb
    ports:
      - "8086:8086"
    secrets:
      - influx-usr
      - influx-psswd

  vscode:
    container_name: vscode
    image: lscr.io/linuxserver/code-server
    volumes:
      - ./codeserver/config:/config
      - ./ha/config:/data
      - .codeserver/vsixs:/installs
    ports:
      - "8765:8443"
    environment:
      - PUID=1000
      - PGID=1002
      - TZ=America/Chicago
      - DEFAULT_WORKSPACE=/nas/docker/homeassistant/config
      - FILE__PASSWORD=/run/secrets/vscode-psswd
    restart: unless-stopped
    secrets:
      - vscode-psswd

  esphome:
    container_name: esphome
    image: esphome/esphome
    command: dashboard --username andy --password "${ESPHOME_PSSWD}" /config
    environment:
      - TZ=America/Chicago
      - ESPHOME_DASHBOARD_USE_PING=true
    network_mode: host
    ports:
      - 6052:6052
      - 6123:6123
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./esphome/config:/config

  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    shm_size: "64mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/config/:/config/:ro
      - ./frigate/media/frigate:/media/frigate
    ports:
      - "5555:5000"
      - "1935:1935" # RTMP feeds
    env_file:
      - ./frigate/.env

  homeassistant:
    container_name: homeassistant
    image: lscr.io/linuxserver/homeassistant:latest
    depends_on:
      postgresdb:
        condition: service_healthy
      influxdb:
        condition: service_healthy
    devices:
      - "/dev/hidraw0:/dev/hidraw0"
    environment:
      - PUID=1000
      - PGID=1002
      - TZ=America/Chicago
    volumes:
      - /run/dbus:/run/dbus:ro
      - ./ha/config:/config
      - /etc/localtime:/etc/localtime:ro
      - ./ha/scripts:/custom-cont-init.d:ro
    restart: unless-stopped
    network_mode: host
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.2.0.0/20
secrets:
  postgres-usr:
    file: ./postgres/usr.txt
  postgres-psswd:
    file: ./postgres/psswd.txt
  influx-usr:
    file: ./influxdb/usr.txt
  influx-psswd:
    file: ./influxdb/psswd.txt
  vscode-psswd:
    file: ./codeserver/psswd.txt
