services:
  mosquitto:
    container_name: mosquitto
    image:  eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 9001:9001
    environment:
      - TZ=America/Chicago
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    privileged: true
    ports:
      - 9442:9442
    volumes:
      - ./zigbee/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      # path to zigbee USB device
      - /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
    environment:
      - TZ=America/Chicago

  zwave:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    devices:
      - /dev/serial/by-id/usb-0658_0200-if00:/dev/zwave
    volumes:
      - ./zwavejs/store:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for zwave-js websocket server

  rtlamr:
    container_name: rtlamr2mqtt
    image: allangood/rtlamr2mqtt
    restart: unless-stopped
    devices:
      - /dev/bus/usb
    volumes:
      - ./rtlamr2mqtt/rtlamr2mqtt.yaml:/etc/rtlamr2mqtt.yaml:ro
      - ./rtlamr2mqtt/data:/var/lib/rtlamr2mqtt

#  postgresdb:
#    image: postgres:16-alpine
#    container_name: postgres
#    ports:
#      - "5432:5432"
#    #network_mode: bridge
#    restart: unless-stopped
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready"]
#      interval: 30s
#      timeout: 5s
#      retries: 60
#    volumes:
#      - /etc/localtime:/etc/localtime
#      - ./postgres/data:/var/lib/postgresql/data
#    env_file:
#      - ./postgres/.env

#  influxdb:
#    container_name: influxdb
#    image: influxdb:latest
#    restart: unless-stopped
#    #network_mode: bridge
#    environment:
#      - INFLUXDB_REPORTING_DISABLED=false
#      - DOCKER_INFLUXDB_INIT_USERNAME_FILE=/run/secrets/influx-usr
#      - DOCKER_INFLUXDB_INIT_PASSWORD_FILE=/run/secrets/influx-psswd
#      - DOCKER_INFLUXDB_INIT_ORG=salmeister
#      - DOCKER_INFLUXDB_INIT_BUCKET=homeassistant
#    healthcheck:
#      test: influx ping || exit 1
#      interval: 30s
#      timeout: 5s
#      retries: 60
#    volumes:
#      - ./influxdb/data:/var/lib/influxdb
#      - ./influxdb/dataV2:/var/lib/influxdb2
#    ports:
#      - "8086:8086"
#    secrets:
#      - influx-usr
#      - influx-psswd

  vscode:
    container_name: vscode
    image: linuxserver/code-server
    volumes:
      - ./codeserver/config:/config
      - ./ha/config:/data
      - ./codeserver/vsixs:/installs
    ports:
      - "8765:8443"
    environment:
      - PUID=1000
      - PGID=1002
      - TZ=America/Chicago
      - DEFAULT_WORKSPACE=/data
      - FILE__PASSWORD=/run/secrets/vscode-psswd
    restart: unless-stopped
    secrets:
      - vscode-psswd

  esphome:
    container_name: esphome
    image: esphome/esphome
    command: dashboard --username andy --password "${ESPHOME_PSSWD}" /config
    environment:
      - TZ=America/Chicago
      - ESPHOME_DASHBOARD_USE_PING=true
    #network_mode: host
    ports:
      - 6052:6052
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./esphome/config:/config

  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb"
    devices:
      - "/dev/apex_0:/dev/apex_0"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/config/:/config
      - ./frigate/media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5555:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    env_file:
      - ./frigate/.env

  homeassistant:
    container_name: homeassistant
    image: linuxserver/homeassistant:latest
#    depends_on:
#      postgresdb:
#        condition: service_healthy
#      influxdb:
#        condition: service_healthy
    devices:
      - "/dev/hidraw0:/dev/hidraw0"
    environment:
      - PUID=1000
      - PGID=1002
      - TZ=America/Chicago
    volumes:
      - /run/dbus:/run/dbus:ro
      - ./ha/config:/config
      - /etc/localtime:/etc/localtime:ro
      - ./ha/scripts:/custom-cont-init.d:ro
    restart: unless-stopped
    network_mode: host
    #ports:
    #  - 8123:8123 #optional
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.2.0.0/20
secrets:
#  influx-usr:
#    file: ./influxdb/usr.txt
#  influx-psswd:
#    file: ./influxdb/psswd.txt
  vscode-psswd:
    file: ./codeserver/psswd.txt
