services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1002
      - TZ=America/Chicago
      - JELLYFIN_PublishedServerUrl=192.168.1.3 #optional
    devices:
      - /dev/dri:/dev:dri
    volumes:
      - ./config:/config
      - ./transcode:/transcode
      - /nas/tv_content/TV_Shows:/tv_shows
      - /nas/tv_content/Movies:/movies
      - /nas/home_content/Videos:/videos
      - /nas/home_content/Pictures:/pictures
      - /nas/home_content/Music:/music
      - /nas/tv_content/Workouts:/workouts
      - /nas/tv_content/Recorded_TV:/recorded_tv
    ports:
      - 8096:8096
      #- 8920:8920 #optional
      - 7359:7359/udp #optional
      #- 1900:1900/udp #optional
    restart: unless-stopped
