services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1002
      - TZ=America/Chicago
      - REDIS_HOST=nextcloud-redis
      - REDIS_PORT=6379
      - REDIS_HOST_PASSWORD=${REDIS_PSSWD}
    ports:
      - 4443:443
    volumes:
      - /nas/docker/nextcloud/config:/config
      - /nas/docker/nextcloud/data:/data
      - /nas/home_content/Media-Import:/mnt/Media-Import
    depends_on:
      nextcloud-db:
        condition: service_healthy
      nextcloud-redis:
        condition: service_healthy
    restart: unless-stopped
  nextcloud-db:
    image: lscr.io/linuxserver/mariadb
    container_name: nextcloud-db
    environment:
      - PUID=1000
      - PGID=1002
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PSSWD}
      - TZ=America/Chicago
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=ncuser
      - MYSQL_PASSWORD=${DB_PSSWD}
    volumes:
      - /nas/docker/nextcloud/db/config:/config
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped
  nextcloud-redis:
    image: redis
    container_name: nextcloud-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PSSWD}
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 30
