services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    environment:
      - TZ=America/Chicago
      - REDIS_HOST=nextcloud-redis
      - REDIS_PORT=6379
      - REDIS_HOST_PASSWORD=${REDIS_PSSWD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=ncuser
      - MYSQL_PASSWORD=${DB_PSSWD}
      - MYSQL_HOST=nextcloud-db
    ports:
      - 8001:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/var/www/html/config
      - ./data:/var/www/html/data
      - /nas/home_content/Media-Import:/mnt/Media-Import
    depends_on:
      nextcloud-db:
        condition: service_healthy
      nextcloud-redis:
        condition: service_healthy
    restart: unless-stopped
  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PSSWD}
      - TZ=America/Chicago
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=ncuser
      - MYSQL_PASSWORD=${DB_PSSWD}
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped
  nextcloud-redis:
    image: redis
    container_name: nextcloud-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PSSWD}
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 30
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.3.0.0/20
