version: '3.2'

services:
  web:
    container_name: motioneye
    hostname: motioneye
    image: ccrisan/motioneye:master-amd64
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /nas/docker/motioneye/etc:/etc/motioneye
      - /nas/docker/motioneye/var/lib:/var/lib/motioneye
    environment:
     - TZ=America/Chicago
    ports:
     - "8765:8765"