version: "2.1"
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    privileged: true
    ports:
      - 9442:9442
    volumes:
      - /nas/docker/zigbee/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      # path to zigbee USB device
      - /dev/ttyUSB0
    environment:
      - TZ=US/Central
