services:
  postfix:
    container_name: postfix
    image: boky/postfix
    restart: unless-stopped
    #network_mode: host
    environment:
      - POSTFIX_myhostname=postfix
      - RELAYHOST=smtp.gmail.com:587
      - RELAYHOST_USERNAME=andrewsalmela@gmail.com
      - RELAYHOST_PASSWORD_FILE=/run/secrets/apppwd
      - ALLOWED_SENDER_DOMAINS=gmail.com salmeister.com
      - POSTFIX_mynetworks=127.0.0.0/8,172.17.0.0/24,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,173.25.125.84/32
      - POSTFIX_smtp_tls_security_level=encrypt
    ports:
      - 587:587
    secrets:
      - apppwd
      - email
secrets:
  apppwd:
    file: ./apppwd.txt
  email:
    file: ./email.txt
