version: '3.7'

services:
  db:
    container_name: influxdb
    image: influxdb:1.8.5
    restart: unless-stopped
    network_mode: bridge
    environment:
      - INFLUXDB_REPORTING_DISABLED=false
      - INFLUXDB_ADMIN_USER_FILE=/run/secrets/usr
      - INFLUXDB_ADMIN_PASSWORD_FILE=/run/secrets/psswd
    volumes:
      - /nas/docker/influxdb/data:/var/lib/influxdb
    ports:
     - "8086:8086"
    secrets:
     - usr
     - psswd
secrets:
  usr:
    file: usr.txt
  psswd:
    file: ./psswd.txt
