version: '3.2'

services:
  web:
    container_name: keeweb
    image: antelle/keeweb:latest
    restart: unless-stopped
    ports:
      - '8987:80'
      - '4987:443'
#    volumes:
#      - /nas/docker/keeweb/data:/etc/nginx/external
