version: '3.7'

services:
    transmission-openvpn:
        image: haugene/transmission-openvpn:latest
        container_name: transmission
        restart: always
        logging:
          driver: json-file
          options:
            max-size: 10m
        volumes:
            - /nas/docker/transmission/openvpn-configs:/etc/openvpn/custom/
            - /nas/docker/transmission/data:/data
            - /etc/localtime:/etc/localtime:ro
        environment:
            - OPENVPN_USERNAME=${USR}
            - OPENVPN_PASSWORD=${PSSWD}
            - OPENVPN_PROVIDER=CUSTOM
            - OPENVPN_CONFIG=Canada-East
            - LOCAL_NETWORK=192.168.1.0/24
            - PUID=1000
            - GUID=1002
        cap_add:
            - NET_ADMIN
        ports:
            - 9091:9091
