services:
    transmission-openvpn:
        image: haugene/transmission-openvpn:latest
        container_name: transmission
        restart: always
        logging:
          driver: json-file
          options:
            max-size: 10m
        volumes:
            - ./openvpn-configs:/etc/openvpn/custom/
            - ./data:/data
            - /etc/localtime:/etc/localtime:ro
        env_file:
          - ./.env
        cap_add:
            - NET_ADMIN
        ports:
            - 9091:9091
