version: '3.2'

services:
  web:
    container_name: chronograf
    image: chronograf:latest
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - /nas/docker/chronograf/data:/var/lib/chronograf
    environment:
      - INFLUXDB_URL=http://192.168.1.3:8086
      - INFLUXDB_USERNAME=user
      - INFLUXDB_PASSWORD=password
