version: '3.7'

services:
  web:
    container_name: chronograf
    image: chronograf:latest
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - /nas/docker/chronograf/data:/var/lib/chronograf
    environment:
      - INFLUXDB_URL=${URL}
      - INFLUXDB_USERNAME=${USR}
      - INFLUXDB_PASSWORD=${PSSWD}
