version: '3.1'
services:
  letsencrypt: # https://github.com/linuxserver/docker-letsencrypt
    container_name: letsencrypt
    image: linuxserver/letsencrypt:latest
    restart: unless-stopped
    cap_add:
    - NET_ADMIN
    volumes:
    - /nas/docker/letsencrypt/config:/config
    - /etc/localtime:/etc/localtime:ro
    environment:
    - PGID=1002
    - PUID=1000
    - FILE__URL=/run/secrets/url
    - SUBDOMAINS=wildcard
    - VALIDATION=dns
    - DNSPLUGIN=cloudflare
    - TZ=America/Chicago
#    - STAGING=true
    ports:
    - "80:80"
    - "443:443"
    secrets:
    - url
secrets:
  url:
    file: url.txt
