version: '3.6'
services:
  esphome:
    container_name: esphome
    image: esphome/esphome
    environment:
      - TZ=America/Chicago
      - ESPHOME_DASHBOARD_USE_PING=true
    network_mode: host
    ports:
      - 6052:6052
      - 6123:6123
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /nas/docker/esphome/config:/config
