version: "3.7"
services:
    db:
        image: "postgres:latest"
        container_name: "postgres"
        ports:
            - "5432:5432"
        network_mode: bridge
        restart: unless-stopped
        environment:
            - POSTGRES_DB=homeassistant
            - POSTGRES_USER_FILE=/run/secrets/usr
            - POSTGRES_PASSWORD_FILE=/run/secrets/psswd
        volumes:
            - /etc/localtime:/etc/localtime
            - /nas/docker/postgres/hass:/var/lib/postgresql/data
        secrets:
            - usr
            - psswd
secrets:
    usr:
      file: usr.txt
    psswd:
      file: psswd.txt
